export const storageConstants = {
    "NOBOX_CLIENT_TOKEN": "NOBOX_CLIENT_TOKEN",
    "NOBOX_DATA": "NOBOX_DATA",
    "NOBOX_SHARED_DATA": "NOBOX_SHARED_DATA",
    "NOBOX_SHARED_PROJECT_TOKENS": "NOBOX_SHARED_PROJECT_TOKENS",
    "NOBOX_RECORDS": "NOBOX_RECORDS",
}